# Generated by Django 4.1.3 on 2023-01-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfer',
            name='portfolio',
        ),
    ]
