# Generated by Django 4.1.3 on 2023-01-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_golfer_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
