# Generated by Django 4.1.3 on 2023-01-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_golfer_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfer',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='golfer',
            name='user',
        ),
        migrations.AddField(
            model_name='golfer',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfer',
            name='last_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
