# Generated by Django 4.1.3 on 2023-01-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_golfer_picture_remove_golfer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='hcp_index',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
