# Generated by Django 4.1.3 on 2023-05-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_golfer',
            name='bet_winnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
