# Generated by Django 4.1.3 on 2023-01-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_golfer',
            name='team',
        ),
    ]
