# Generated by Django 4.1.3 on 2023-03-25 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_teetime',
            name='Winning_Team',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_team'),
            preserve_default=False,
        ),
    ]
