# Generated by Django 4.1.3 on 2023-01-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip_event',
            old_name='Course',
            new_name='course',
        ),
    ]
