# Generated by Django 4.1.3 on 2023-01-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_event',
            name='event_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip_teetime',
            name='tee_time',
            field=models.DateTimeField(),
        ),
    ]
