# Generated by Django 4.1.3 on 2023-02-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0003_alter_trip_teetime_gametype'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_teetime',
            name='teeTime_Complete',
            field=models.BooleanField(default=False),
        ),
    ]
