# Generated by Django 4.1.3 on 2023-03-16 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0005_alter_trip_golfer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_team',
            name='members',
            field=models.ManyToManyField(through='golf_trip.Trip_TeamMember', to='golf_trip.trip_golfer'),
        ),
        migrations.AlterField(
            model_name='trip_teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_trip.trip_golfer'),
        ),
    ]
