# Generated by Django 4.1.3 on 2022-12-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golf_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Golf_Tee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tee_color', models.CharField(max_length=25, unique=True)),
                ('tee_name', models.CharField(max_length=25, unique=True)),
                ('par', models.IntegerField()),
                ('slope', models.FloatField()),
                ('rating', models.FloatField()),
                ('yardage', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tee_course', to='Courses.golf_course')),
            ],
            options={
                'unique_together': {('course', 'tee_color')},
            },
        ),
        migrations.CreateModel(
            name='Golf_Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.IntegerField()),
                ('par', models.IntegerField()),
                ('yardage', models.IntegerField()),
                ('hcp_index', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_course', to='Courses.golf_course')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_tee', to='Courses.golf_tee')),
            ],
            options={
                'unique_together': {('course', 'tee', 'hole_number')},
            },
        ),
        migrations.CreateModel(
            name='Golf_Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_course', to='Courses.golf_course')),
                ('hole_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_hole_1', to='Courses.golf_hole')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_tee', to='Courses.golf_tee')),
            ],
            options={
                'unique_together': {('course', 'tee')},
            },
        ),
    ]
