# Generated by Django 4.1.3 on 2022-12-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='golf_tee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='tee_name',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='golf_tee',
            unique_together={('course_name', 'tee_name')},
        ),
        migrations.RemoveField(
            model_name='golf_tee',
            name='golf_tee_name',
        ),
    ]
