# Generated by Django 4.1.3 on 2022-12-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golf_tee',
            name='hole_10_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_10_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_10_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_11_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_11_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_11_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_12_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_12_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_12_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_13_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_13_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_13_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_14_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_14_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_14_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_15_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_15_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_15_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_16_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_16_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_16_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_17_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_17_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_17_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_18_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_18_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_18_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_2_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_2_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_2_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_3_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_3_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_3_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_4_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_4_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_4_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_5_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_5_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_5_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_6_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_6_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_6_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_7_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_7_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_7_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_8_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_8_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_8_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_9_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_9_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AddField(
            model_name='golf_tee',
            name='hole_9_yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='golf_tee',
            name='hole_1_index',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18)], default=1),
        ),
        migrations.AlterField(
            model_name='golf_tee',
            name='hole_1_par',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], default=4),
        ),
        migrations.AlterField(
            model_name='golf_tee',
            name='hole_1_yardage',
            field=models.IntegerField(default=0),
        ),
    ]
