# Generated by Django 4.1.3 on 2022-12-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_alter_golf_tee_unique_together_golf_tee_tee_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='golf_hole',
            unique_together={('referred_tee_name', 'hole_number')},
        ),
        migrations.RemoveField(
            model_name='golf_hole',
            name='course_name',
        ),
    ]
