# Generated by Django 4.1.3 on 2023-01-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_alter_golf_tee_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_tee',
            name='course',
            field=models.ForeignKey(default='please select', on_delete=django.db.models.deletion.CASCADE, related_name='golf_tees', to='Courses.golf_course', unique=True),
        ),
    ]
