# Generated by Django 4.1.3 on 2022-12-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_rename_course_golf_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_tee',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='golf_tee',
            name='slope',
            field=models.FloatField(),
        ),
    ]
