# Generated by Django 4.1.3 on 2022-12-23 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_golf_tee_rating_alter_golf_tee_slope'),
    ]

    operations = [
        migrations.AddField(
            model_name='golf_course',
            name='tee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_tee', to='Courses.golf_tee'),
        ),
    ]
