# Generated by Django 4.1.3 on 2023-01-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_golf_tee_9_hole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_tee',
            name='course',
            field=models.ForeignKey(default='please select', on_delete=django.db.models.deletion.CASCADE, related_name='golf_tees', to='Courses.golf_course'),
        ),
    ]
