# Generated by Django 4.1.3 on 2023-01-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_golf_tee_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_tee',
            name='tee_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='golf_tee_9_hole',
            name='course',
            field=models.ForeignKey(default='please select', on_delete=django.db.models.deletion.CASCADE, related_name='golf_tees_9', to='Courses.golf_course'),
        ),
        migrations.AlterField(
            model_name='golf_tee_9_hole',
            name='tee_name',
            field=models.CharField(max_length=255),
        ),
    ]
