from django.db import models
from golf_trip.models import Trip_TeeTime


    

class Round_Score(models.Model):
    tee_time = models.ForeignKey(Trip_TeeTime, on_delete=models.PROTECT)
    round_golfer = models.CharField(max_length=255)
    golfer_index = models.DecimalField(decimal_places=1, max_digits=3)
    hole_1_score = models.IntegerField()
    hole_2_score = models.IntegerField()
    hole_3_score = models.IntegerField()
    hole_4_score = models.IntegerField()
    hole_5_score = models.IntegerField()
    hole_6_score = models.IntegerField()
    hole_7_score = models.IntegerField()
    hole_8_score = models.IntegerField()
    hole_9_score = models.IntegerField()
    hole_10_score = models.IntegerField()
    hole_11_score = models.IntegerField()
    hole_12_score = models.IntegerField()
    hole_13_score = models.IntegerField()
    hole_14_score = models.IntegerField()
    hole_15_score = models.IntegerField()
    hole_16_score = models.IntegerField()
    hole_17_score = models.IntegerField()
    hole_18_score = models.IntegerField()
    total_score = models.IntegerField(default=0)
    net_score = models.IntegerField(default=0)

class Net_Round_Score(models.Model):
    raw_round_score = models.ForeignKey(Round_Score, on_delete=models.PROTECT)
    round_golfer = models.CharField(max_length=255)
    hole_1_score = models.IntegerField()
    hole_2_score = models.IntegerField()
    hole_3_score = models.IntegerField()
    hole_4_score = models.IntegerField()
    hole_5_score = models.IntegerField()
    hole_6_score = models.IntegerField()
    hole_7_score = models.IntegerField()
    hole_8_score = models.IntegerField()
    hole_9_score = models.IntegerField()
    hole_10_score = models.IntegerField()
    hole_11_score = models.IntegerField()
    hole_12_score = models.IntegerField()
    hole_13_score = models.IntegerField()
    hole_14_score = models.IntegerField()
    hole_15_score = models.IntegerField()
    hole_16_score = models.IntegerField()
    hole_17_score = models.IntegerField()
    hole_18_score = models.IntegerField()
    total_score = models.IntegerField()
    net_score = models.IntegerField()

