# Generated by Django 4.1.3 on 2023-04-13 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('golf_trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_golfer')),
                ('tee_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_teetime')),
            ],
        ),
        migrations.CreateModel(
            name='TeamVsTeam',
            fields=[
                ('golfbet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookie.golfbet')),
                ('bet_initiator_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiator_team', to='golf_trip.trip_team')),
                ('bet_opponent_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opponet_team', to='golf_trip.trip_team')),
            ],
            bases=('bookie.golfbet',),
        ),
        migrations.CreateModel(
            name='PlayerVsPlayer',
            fields=[
                ('golfbet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookie.golfbet')),
                ('bet_opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_golfer')),
            ],
            bases=('bookie.golfbet',),
        ),
    ]
