# Generated by Django 4.1.3 on 2023-04-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0001_initial'),
        ('bookie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfbet',
            name='bet_winner',
            field=models.ForeignKey(blank=True, default='N/A', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='golf_trip.trip_golfer'),
        ),
    ]
