# Generated by Django 4.1.3 on 2023-04-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0003_golfbet_units_currency_alter_golfbet_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfbet',
            name='units_currency',
        ),
        migrations.AlterField(
            model_name='golfbet',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
