# Generated by Django 4.1.3 on 2023-01-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammember_delete_groupmember_alter_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
