# Generated by Django 4.1.3 on 2023-01-06 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_golfer_picture'),
        ('Courses', '0002_alter_golf_tee_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Golf_Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_round', models.BooleanField(default=False)),
                ('round_create_date', models.DateTimeField(default=datetime.datetime(2023, 1, 6, 13, 7, 58, 139935, tzinfo=datetime.timezone.utc))),
                ('hole_1_score', models.IntegerField(blank=True, default=0)),
                ('hole_2_score', models.IntegerField(blank=True, default=0)),
                ('hole_3_score', models.IntegerField(blank=True, default=0)),
                ('hole_4_score', models.IntegerField(blank=True, default=0)),
                ('hole_5_score', models.IntegerField(blank=True, default=0)),
                ('hole_6_score', models.IntegerField(blank=True, default=0)),
                ('hole_7_score', models.IntegerField(blank=True, default=0)),
                ('hole_8_score', models.IntegerField(blank=True, default=0)),
                ('hole_9_score', models.IntegerField(blank=True, default=0)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.golfer')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.golf_tee')),
            ],
        ),
    ]
