# Generated by Django 4.1.3 on 2023-04-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('golf_trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_golfer', models.CharField(max_length=255)),
                ('golfer_index', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hole_1_score', models.IntegerField()),
                ('hole_2_score', models.IntegerField()),
                ('hole_3_score', models.IntegerField()),
                ('hole_4_score', models.IntegerField()),
                ('hole_5_score', models.IntegerField()),
                ('hole_6_score', models.IntegerField()),
                ('hole_7_score', models.IntegerField()),
                ('hole_8_score', models.IntegerField()),
                ('hole_9_score', models.IntegerField()),
                ('hole_10_score', models.IntegerField()),
                ('hole_11_score', models.IntegerField()),
                ('hole_12_score', models.IntegerField()),
                ('hole_13_score', models.IntegerField()),
                ('hole_14_score', models.IntegerField()),
                ('hole_15_score', models.IntegerField()),
                ('hole_16_score', models.IntegerField()),
                ('hole_17_score', models.IntegerField()),
                ('hole_18_score', models.IntegerField()),
                ('total_score', models.IntegerField(default=0)),
                ('net_score', models.IntegerField(default=0)),
                ('tee_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_teetime')),
            ],
        ),
        migrations.CreateModel(
            name='Net_Round_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_golfer', models.CharField(max_length=255)),
                ('hole_1_score', models.IntegerField()),
                ('hole_2_score', models.IntegerField()),
                ('hole_3_score', models.IntegerField()),
                ('hole_4_score', models.IntegerField()),
                ('hole_5_score', models.IntegerField()),
                ('hole_6_score', models.IntegerField()),
                ('hole_7_score', models.IntegerField()),
                ('hole_8_score', models.IntegerField()),
                ('hole_9_score', models.IntegerField()),
                ('hole_10_score', models.IntegerField()),
                ('hole_11_score', models.IntegerField()),
                ('hole_12_score', models.IntegerField()),
                ('hole_13_score', models.IntegerField()),
                ('hole_14_score', models.IntegerField()),
                ('hole_15_score', models.IntegerField()),
                ('hole_16_score', models.IntegerField()),
                ('hole_17_score', models.IntegerField()),
                ('hole_18_score', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('net_score', models.IntegerField()),
                ('tee_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_teetime')),
            ],
        ),
    ]
