# Generated by Django 4.1.3 on 2023-05-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0001_initial'),
        ('GolfRound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='net_round_score',
            name='round_golfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_golfer'),
        ),
        migrations.AlterField(
            model_name='round_score',
            name='round_golfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_golfer'),
        ),
    ]
