# Generated by Django 4.1.3 on 2023-01-04 20:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GolfRound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round_player',
            name='course',
        ),
        migrations.AddField(
            model_name='round_player',
            name='round',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GolfRound.golf_round'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='golf_round',
            name='round_create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 20, 11, 29, 455169, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='round_player',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 20, 11, 29, 455501, tzinfo=datetime.timezone.utc)),
        ),
    ]
