# Generated by Django 4.1.3 on 2023-05-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0001_initial'),
        ('GolfRound', '0002_alter_net_round_score_round_golfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='net_round_score',
            name='golfer_pk',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_golfer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round_score',
            name='golfer_pk',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_golfer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='net_round_score',
            name='round_golfer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='round_score',
            name='round_golfer',
            field=models.CharField(max_length=255),
        ),
    ]
