# Generated by Django 4.1.3 on 2023-01-13 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfRound', '0002_alter_round_submission_round_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_submission',
            name='round_submission_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 17, 19, 26, 375503, tzinfo=datetime.timezone.utc)),
        ),
    ]
