# Generated by Django 4.1.3 on 2023-01-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0002_remove_trip_golfer_team'),
        ('GolfRound', '0002_alter_round_submission_round_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round_score',
            name='submission',
        ),
        migrations.AddField(
            model_name='round_score',
            name='tee_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_teetime'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Round_Submission',
        ),
    ]
