# Generated by Django 4.1.3 on 2023-01-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfRound', '0002_remove_round_player_course_round_player_round_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round_Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.IntegerField(default='0')),
                ('hole_score', models.IntegerField(default='0')),
            ],
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_10_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_11_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_12_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_13_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_14_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_15_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_16_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_17_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_18_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_1_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_2_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_3_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_4_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_5_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_6_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_7_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_8_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_9_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='round',
        ),
        migrations.DeleteModel(
            name='Golf_Round',
        ),
        migrations.AddField(
            model_name='round_player',
            name='score_hole',
            field=models.ManyToManyField(to='GolfRound.round_hole'),
        ),
    ]
