# Generated by Django 4.1.3 on 2023-01-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfRound', '0003_round_hole_remove_round_player_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_player',
            name='hole_1_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='round_player',
            name='hole_2_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='round_player',
            name='hole_3_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='round_player',
            name='hole_4_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='round_player',
            name='hole_5_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='round_player',
            name='hole_6_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='round_player',
            name='hole_7_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='round_player',
            name='hole_8_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='round_player',
            name='hole_9_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
