# Generated by Django 4.1.3 on 2023-08-06 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0002_alter_trip_golfer_bet_winnings'),
        ('GolfRound', '0003_net_round_score_golfer_pk_round_score_golfer_pk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Par3_Round_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_golfer', models.CharField(max_length=255)),
                ('golfer_index', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hole_1_score', models.IntegerField()),
                ('hole_2_score', models.IntegerField()),
                ('hole_3_score', models.IntegerField()),
                ('hole_4_score', models.IntegerField()),
                ('hole_5_score', models.IntegerField()),
                ('hole_6_score', models.IntegerField()),
                ('hole_7_score', models.IntegerField()),
                ('hole_8_score', models.IntegerField()),
                ('hole_9_score', models.IntegerField()),
                ('total_score', models.IntegerField(default=0)),
                ('net_score', models.IntegerField(default=0)),
                ('golfer_pk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_golfer')),
                ('tee_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_teetime')),
            ],
        ),
        migrations.CreateModel(
            name='Par3_Net_Round_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_golfer', models.CharField(max_length=255)),
                ('hole_1_score', models.IntegerField()),
                ('hole_2_score', models.IntegerField()),
                ('hole_3_score', models.IntegerField()),
                ('hole_4_score', models.IntegerField()),
                ('hole_5_score', models.IntegerField()),
                ('hole_6_score', models.IntegerField()),
                ('hole_7_score', models.IntegerField()),
                ('hole_8_score', models.IntegerField()),
                ('hole_9_score', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('net_score', models.IntegerField()),
                ('golfer_pk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_golfer')),
                ('tee_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_teetime')),
            ],
        ),
    ]
