# Generated by Django 4.1.3 on 2023-01-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GolfRound', '0004_round_player_hole_1_score_round_player_hole_2_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round_player',
            name='hole_1_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_2_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_3_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_4_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_5_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_6_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_7_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_8_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='hole_9_score',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='score_hole',
        ),
        migrations.AddField(
            model_name='round_player',
            name='score_hole',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GolfRound.round_hole'),
        ),
    ]
