# Generated by Django 4.1.3 on 2023-01-06 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_golfer_picture'),
        ('Courses', '0002_alter_golf_tee_course'),
        ('GolfRound', '0004_alter_golf_round_round_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_round',
            name='round_create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 16, 1, 23, 465253, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Round_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('round_submission_date', models.DateTimeField(default=datetime.datetime(2023, 1, 6, 16, 1, 23, 465768, tzinfo=datetime.timezone.utc))),
                ('golfer_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='accounts.golfer')),
                ('golfer_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='accounts.golfer')),
                ('golfer_3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_3', to='accounts.golfer')),
                ('golfer_4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_4', to='accounts.golfer')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.golf_tee')),
            ],
        ),
    ]
