# Generated by Django 4.1.3 on 2023-01-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfRound', '0005_net_round_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_score',
            name='net_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='round_score',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
