# Generated by Django 4.1.3 on 2023-01-05 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
        ('accounts', '0003_alter_golfer_picture'),
        ('GolfRound', '0005_remove_round_player_hole_1_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Golf_Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_round', models.BooleanField(default=False)),
                ('round_create_date', models.DateTimeField(default=datetime.datetime(2023, 1, 5, 17, 12, 5, 850087, tzinfo=datetime.timezone.utc))),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.golf_tee')),
            ],
        ),
        migrations.CreateModel(
            name='Round_Hole_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_1_score', models.IntegerField(blank=True, default=0)),
                ('hole_2_score', models.IntegerField(blank=True, default=0)),
                ('hole_3_score', models.IntegerField(blank=True, default=0)),
                ('hole_4_score', models.IntegerField(blank=True, default=0)),
                ('hole_5_score', models.IntegerField(blank=True, default=0)),
                ('hole_6_score', models.IntegerField(blank=True, default=0)),
                ('hole_7_score', models.IntegerField(blank=True, default=0)),
                ('hole_8_score', models.IntegerField(blank=True, default=0)),
                ('hole_9_score', models.IntegerField(blank=True, default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.golfer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GolfRound.golf_round')),
            ],
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='player',
        ),
        migrations.RemoveField(
            model_name='round_player',
            name='score_hole',
        ),
        migrations.DeleteModel(
            name='Round_Hole',
        ),
        migrations.DeleteModel(
            name='Round_Player',
        ),
    ]
