# Generated by Django 4.1.3 on 2023-01-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0003_alter_trip_teetime_gametype'),
        ('GolfRound', '0006_alter_round_score_net_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net_round_score',
            name='raw_round_score',
        ),
        migrations.AddField(
            model_name='net_round_score',
            name='tee_time',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_teetime'),
            preserve_default=False,
        ),
    ]
