# Generated by Django 4.1.3 on 2023-01-05 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfRound', '0006_golf_round_round_hole_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_round',
            name='round_create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 17, 17, 15, 366793, tzinfo=datetime.timezone.utc)),
        ),
    ]
