# Generated by Django 4.1.3 on 2023-01-05 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_alter_golf_tee_course'),
        ('GolfRound', '0007_alter_golf_round_round_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='golf_round',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='round_source', to='Courses.golf_tee', to_field='course', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='golf_round',
            name='round_create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 17, 27, 33, 538762, tzinfo=datetime.timezone.utc)),
        ),
    ]
