# Generated by Django 4.1.3 on 2023-01-26 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_trip', '0003_alter_trip_teetime_gametype'),
        ('GolfRound', '0007_remove_net_round_score_raw_round_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='net_round_score',
            name='round_golfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_golfer'),
        ),
        migrations.AlterField(
            model_name='round_score',
            name='round_golfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golf_trip.trip_golfer'),
        ),
    ]
