# Generated by Django 4.1.3 on 2023-02-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfRound', '0008_alter_net_round_score_round_golfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='net_round_score',
            name='round_golfer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='round_score',
            name='round_golfer',
            field=models.CharField(max_length=255),
        ),
    ]
