# Generated by Django 4.1.3 on 2023-01-09 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_golfer_hcp_index'),
        ('GolfRound', '0009_alter_golf_round_round_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_1_score', models.IntegerField(default=0)),
                ('hole_2_score', models.IntegerField(default=0)),
                ('hole_3_score', models.IntegerField(default=0)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_score', to='accounts.golfer')),
            ],
        ),
        migrations.AlterField(
            model_name='round_submission',
            name='round_submission_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 14, 41, 50, 845961, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Golf_Round',
        ),
    ]
